version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
     #- docker pull poei-wordpress:latest
      #- docker build -t poei-wordpress .

      #- docker build -t wordpress-container ./docker/wordpress/
      #- docker tag wordpress-container:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/poei-wordprss:latest
  post_build:
    commands:
     # - echo Build completed on `date`
      #- echo Pushing the Docker image...
      #- docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/poei-wordpress:latest

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.m2/**/*'

