apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: prod
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 2  # Plus de réplicas pour la haute disponibilité
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
        - name: WORDPRESS_DB_USER
          value: wordpressuser
        - name: WORDPRESS_DB_PASSWORD
          value: wordpresspass
        - name: WORDPRESS_DB_NAME
          value: wordpress
        ports:
        - containerPort: 80
