apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-prod
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Plus d'espace pour la production
  storageClassName: "gp2"  # Exemple pour AWS
 