apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Moins d'espace requis en développement
  storageClassName: "standard"
