version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform and kubectl..."
      - wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
      - unzip terraform_0.15.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - cd iac/
      - terraform init
      - echo "Validate Terraform deployment..."
      - terraform validate
      
  build:
    commands:
      - echo "Applying Terraform configuration..."
      
  post_build:
    commands:
      - echo "Configuring kubectl for EKS cluster..."
     
