version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform and kubectl..."
      - wget https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip terraform_1.7.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version
      
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - cd iac/
      - terraform init
      - echo "Validate Terraform deployment..."
      - terraform validate
      - echo "Planning Terraform deployment..."
      - terraform plan
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 885801475464.dkr.ecr.eu-west-3.amazonaws.com/ecr-poei-web1-frontend
      - cd ..
      
  build:
    commands:
      - echo "Applying Terraform configuration..."
      - cd iac/
      - terraform apply -auto-approve
      - echo "Terraform apply complete."
      - cd ..
      - echo "Building and pushing Docker images..."
      
  post_build:
    commands:
      - cd k8s/ 
      - echo "Configuring kubectl for EKS cluster..."
      - aws eks --region eu-west-3 update-kubeconfig --name cluster-poei
      - echo "Deploying Kubernetes manifests..."
      - kubectl create namespace prod
      - echo "Namespace prod created succeful"
      - kubectl apply -f prod/maradb -n prod
      - kubectl apply -f prod/wordpress -n prod
      - kubectl apply -f prod/cert-manager -n prod
      - kubectl apply -f prod/ingress.yaml -n prod
      - echo "Deployment to Kubernetes completed."
      
      