apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc-prod
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Plus d'espace pour la base de données en production
  storageClassName: "gp2"  # Exemple pour AWS
  